services:
  - type: worker
    name: kairozen-bot-hosting
    env: python
    plan: starter
    buildCommand: pip install -r requirements.txt
    startCommand: python fils.py
    envVars:
      - key: BOT_TOKEN
        sync: false
      - key: ADMIN_ID
        sync: false
      - key: DATA_DIR
        value: /data
    disk:
      name: bot-data
      mountPath: /data
      sizeGB: 1
